services:
  nats:
    image: nats:alpine

  client:
    build:
      context: .
    develop:
      watch:
        - path: composer.json
          action: rebuild
        - path: composer.lock
          action: rebuild
        - path: .
          target: /var/www
          action: sync+restart
          ignore:
            - vendor/
            - compose.yml
            - Dockerfile
            - Makefile