server_name: n3
port: 4222
http_port: 8222
client_advertise: "n3:4222"

tls {
  cert_file: "/etc/nats/certs/n3.pem"
  key_file: "/etc/nats/certs/n3-key.pem"
  ca_file: "/etc/nats/certs/ca.pem"
  verify: true
}

cluster {
  name: "it-cluster-tls"
  port: 6222
  routes = [
    nats://n1:6222
    nats://n2:6222
  ]
}
